spring:
    application:
        name: enviroment-variables
    datasource:
        url: ${DATASOURCE_URL:jdbc:mysql://localhost:3308/demo}
        password: ${DATASOURCE_PASSWORD:root}
        username: ${DATASOURCE_USERNAME:Coder_1234}
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        generate-ddl: true
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect


